Aanpassingen n.a.v. expiration van BAG Huidige Bevragingen
VNG-Realisatie/BAG-Gemeentelijke-wensen-tav-BAG-Bevragingen pull request #562
Opened 2024-01-04 09:02 UTC by melsk-r

O.a.:
* Aanpassingen n.a.v. de expiration van HC BAG Huidige Bevragingen
* Check op links en teksten

**LET OP**
- [ ] Wijzig na mergen van dit PR ook de 'develop' branch.

2024-01-08 11:50 UTC, JohanBoer requested changes
Ik denk dat je in de release-notes ook aan moet geven dat de Huidige bevragingen is uitgefaseerd en dat we nu naar een versie (welke?) van de individuele bevragingen verwijzen.  Ik denk dat hier ook toegelicht moet worden dat de Individuele Bevragingen een Kadaster -API is. 
Kopieren wij nu de specificaties van de Kadaster Github repo ? 
Want daar worden de actuele specificaties bijgehouden. Ik denk dus dat we hier zo min mogelijk specificaties moeten publiceren en vooral naar het kadaster moeten verwijzen.

2024-01-08 11:51 UTC, JohanBoer reviewed
Misschien dat we hier samen een keer doorheen moeten lopen met die mindset, of zie jij dat anders ?

2024-01-08 13:22 UTC, melsk-r commented
> Kopieren wij nu de specificaties van de Kadaster Github repo ? Want daar worden de actuele specificaties bijgehouden. Ik denk dus dat we hier zo min mogelijk specificaties moeten publiceren en vooral naar het kadaster moeten verwijzen.

In de redoc en swagger interface wordt `https://raw.githubusercontent.com/lvbag/BAG-API/master/Technische%20specificatie/Archief/Yaml%27s/BAG%20API%20Individuele%20Bevragingen/resolved/individuelebevragingen/v2/openapi.yaml` gebruikt. Ik heb index.md zo aangepast dat hetzelfde bestand onder de link in 'Download de technische specificaties' wordt gebruikt. We verwijzen dus als ik het goed heb nu dus overal naar de specificaties in de repository van het kadaster.

2024-01-08 13:22 UTC, melsk-r commented
> Misschien dat we hier samen een keer doorheen moeten lopen met die mindset, of zie jij dat anders ?

Prima!

2024-02-08 07:57 UTC, melsk-r commented
> Ik denk dat je in de release-notes ook aan moet geven dat de Huidige bevragingen is uitgefaseerd en dat we nu naar een versie (welke?) van de individuele bevragingen verwijzen. Ik denk dat hier ook toegelicht moet worden dat de Individuele Bevragingen een Kadaster -API is.

Releasenotes zijn conform bovenstaande aangepast.

2024-02-19 10:38 UTC, merged